Fix building with Typescript 4.4 due to changed internal interface
matchFiles() has an additional directoryExists argument.

Without this change the build fails with Error: directoryExists is not a function