Disable rule from tslint.json because tslint is no longer compatible with TypeScript 5.x:
The 'no-shadowed-variable' rule threw an error in 'C:/Git/rushstack/build-tests/heft-typescript-composite-test/src/indexA.ts':
TypeError: DeprecationError: 'originalKeywordKind' has been deprecated since v5.0.0 and can no longer be used. Use 'identifierToKeywordKind(identifier)' instead.
    at C:\Git\rushstack\common\temp\node_modules\.pnpm\typescript@5.3.3\node_modules\typescript\lib\typescript.js:172041:13
    at IdentifierObject.<anonymous> (C:\Git\rushstack\common\temp\node_modules\.pnpm\typescript@5.3.3\node_modules\typescript\lib\typescript.js:172071:7)
    at Object.isThisParameter (C:\Git\rushstack\common\temp\node_modules\.pnpm\tsutils@2.29.0_typescript@5.3.3\node_modules\tsutils\util\util.js:36:79)
    at cb (C:\Git\rushstack\common\temp\node_modules\.pnpm\tslint@5.20.1_typescript@5.3.3\node_modules\tslint\lib\rules\noShadowedVariableRule.js:207:36)