Fix logging warnings in TypeScript config
Previously, TypeScriptConfiguration did not correctly log warnings since
the `this.logWarning` function passed by TypeScriptTask lost its binding
to `TypeScriptTask` when passed to TypeScriptConfiguration:

TypeError: Cannot read property 'name' of undefined
    at logWarning (.../node_modules/@microsoft/gulp-core-build/lib/tasks/GulpTask.js:114:45)
    at Function.fixupSettings (.../node_modules/@microsoft/gulp-core-build-typescript/lib/TypeScriptConfiguration.js:94:13)
    at TypeScriptTask.executeTask (.../node_modules/@microsoft/gulp-core-build-typescript/lib/TypeScriptTask.js:73:59)
    at Promise (.../node_modules/@microsoft/gulp-core-build/lib/tasks/GulpTask.js:173:31)
    at new Promise (<anonymous>)
    at TypeScriptTask.execute (.../node_modules/@microsoft/gulp-core-build/lib/tasks/GulpTask.js:165:16)
    at _executeTask (.../node_modules/@microsoft/gulp-core-build/lib/index.js:341:44)
    at output.then (.../node_modules/@microsoft/gulp-core-build/lib/index.js:253:44)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

This is fixed by explicitly binding `logWarning` to `this`.